# Performance-focused analysis options
# include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Performance rules
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_web_libraries_in_flutter: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    # Disable expensive rules for performance
    always_declare_return_types: false
    always_put_control_body_on_new_line: false
